### ISSUE TITLE
토큰 값을 필요로 하는 URI에 토큰 없이 보낼 경우 500 ERROR

### ISSUE THREAD

**Issue by fineman999** [fineman999/TIL#98]
- http://localhost:8080/api/v1/auth/preAuthorize에 원래는 Authorization을 Header에 넣고 Bearer 를 value에 넣어야된다.
- 만약 없이 넣을 경우 NullPointException과 함께 500에러가 발생한다.
- 없이 보낼경우 클라이언트의 잘못으로 생각하므로 한번 4xx에러로 보내게 해보자.

**Comment by fineman999** [comment]
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "exception" is null
	at org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.resolveMethodByThrowable(ExceptionHandlerMethodResolver.java:146) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.method.annotation.ExceptionHandlerMethodResolver.resolveMethod(ExceptionHandlerMethodResolver.java:134) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.getExceptionHandlerMethod(ExceptionHandlerExceptionResolver.java:481) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:383) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:74) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:141) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at io.start.demo.security.config.JwtAuthenticationEntryPoint.commence(JwtAuthenticationEntryPoint.java:27) ~[classes/:na]
	at org.springframework.security.w

**Comment by fineman999** [comment]
NullPointExcetion 때문이 아니다.
Spring Security에서 해당 Authorization 확인하려고 하니 해당 값 자체가 없어서 InsufficientAuthenticationException를 던진다.
그래서 널 포인트와 관련이 없으므로 
기존의 AuthenticationEntryPoint 구현체에 해당 값을 예외처리하는 값을 추가하고 ControllerAdvice에도 추가하자
```java
@Slf4j
@Component
public class JwtAuthenticationEntryPoint implements AuthenticationEntryPoint {

    private final HandlerExceptionResolver resolver;

    public JwtAuthenticationEntryPoint(@Qualifier("handlerExceptionResolver") HandlerExceptionResolver resolver) {
        this.resolver = resolver;
    }

    @Override
    public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException, ServletException {
        log.info("JwtAuthenticationEntryPoint commence");
        log.info("JwtAuthenticationEntryPoint commence authException={}", authException);
        if (authException instanceof InsufficientAuthenticationException) {
            request.setAttribute("exception", authException);
        }
        resolver.resolveException(request, response, null, (Exception) request.getAttribute("exception"));
    }
}
```
